const datatype = @import("../datatype.zig");
const buffer = @import("../buffer.zig");

// Public aggregation module that re-exports all array views/builders.

pub const SharedBuffer = buffer.SharedBuffer;
pub const OwnedBuffer = buffer.OwnedBuffer;

pub const DataType = datatype.DataType;
pub const ArrayData = @import("array_data.zig").ArrayData;
pub const ArrayRef = @import("array_ref.zig").ArrayRef;
pub const PrimitiveArray = @import("primitive_array.zig").PrimitiveArray;
pub const PrimitiveBuilder = @import("primitive_array.zig").PrimitiveBuilder;
pub const Int8Array = PrimitiveArray(i8);
pub const Int16Array = PrimitiveArray(i16);
pub const Int32Array = PrimitiveArray(i32);
pub const Int64Array = PrimitiveArray(i64);
pub const UInt8Array = PrimitiveArray(u8);
pub const UInt16Array = PrimitiveArray(u16);
pub const UInt32Array = PrimitiveArray(u32);
pub const UInt64Array = PrimitiveArray(u64);
pub const Float32Array = PrimitiveArray(f32);
pub const Float64Array = PrimitiveArray(f64);
pub const Int8Builder = PrimitiveBuilder(i8, DataType{ .int8 = {} });
pub const Int16Builder = PrimitiveBuilder(i16, DataType{ .int16 = {} });
pub const Int32Builder = PrimitiveBuilder(i32, DataType{ .int32 = {} });
pub const Int64Builder = PrimitiveBuilder(i64, DataType{ .int64 = {} });
pub const UInt8Builder = PrimitiveBuilder(u8, DataType{ .uint8 = {} });
pub const UInt16Builder = PrimitiveBuilder(u16, DataType{ .uint16 = {} });
pub const UInt32Builder = PrimitiveBuilder(u32, DataType{ .uint32 = {} });
pub const UInt64Builder = PrimitiveBuilder(u64, DataType{ .uint64 = {} });
pub const Float32Builder = PrimitiveBuilder(f32, DataType{ .float = {} });
pub const Float64Builder = PrimitiveBuilder(f64, DataType{ .double = {} });
pub const BooleanArray = @import("boolean_array.zig").BooleanArray;
pub const BooleanBuilder = @import("boolean_array.zig").BooleanBuilder;
pub const StringArray = @import("string_array.zig").StringArray;
pub const LargeStringArray = @import("string_array.zig").LargeStringArray;
pub const StringBuilder = @import("string_array.zig").StringBuilder;
pub const LargeStringBuilder = @import("string_array.zig").LargeStringBuilder;
pub const BinaryArray = @import("binary_array.zig").BinaryArray;
pub const LargeBinaryArray = @import("binary_array.zig").LargeBinaryArray;
pub const BinaryBuilder = @import("binary_array.zig").BinaryBuilder;
pub const LargeBinaryBuilder = @import("binary_array.zig").LargeBinaryBuilder;
pub const ListArray = @import("list_array.zig").ListArray;
pub const LargeListArray = @import("list_array.zig").LargeListArray;
pub const ListBuilder = @import("list_array.zig").ListBuilder;
pub const LargeListBuilder = @import("list_array.zig").LargeListBuilder;
pub const StructArray = @import("struct_array.zig").StructArray;
pub const StructBuilder = @import("struct_array.zig").StructBuilder;
pub const FixedSizeBinaryArray = @import("fixed_size_array.zig").FixedSizeBinaryArray;
pub const FixedSizeBinaryBuilder = @import("fixed_size_array.zig").FixedSizeBinaryBuilder;
pub const FixedSizeListArray = @import("fixed_size_array.zig").FixedSizeListArray;
pub const FixedSizeListBuilder = @import("fixed_size_array.zig").FixedSizeListBuilder;
pub const DictionaryArray = @import("dictionary_array.zig").DictionaryArray;
pub const DictionaryBuilder = @import("dictionary_array.zig").DictionaryBuilder;
pub const MapArray = @import("advanced_array.zig").MapArray;
pub const SparseUnionArray = @import("advanced_array.zig").SparseUnionArray;
pub const DenseUnionArray = @import("advanced_array.zig").DenseUnionArray;
pub const RunEndEncodedArray = @import("advanced_array.zig").RunEndEncodedArray;
pub const MapBuilder = @import("advanced_array.zig").MapBuilder;
pub const SparseUnionBuilder = @import("advanced_array.zig").SparseUnionBuilder;
pub const DenseUnionBuilder = @import("advanced_array.zig").DenseUnionBuilder;
pub const RunEndEncodedBuilder = @import("advanced_array.zig").RunEndEncodedBuilder;
